### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by daniel-w0** [Proximyst/Yuki#1]
So, I've done C++ for 4 years and now want to learn something new, I found the Rust Programming  Language and then I found this hack, I compiled it and injected it but I don't know how to use it. I see it used ImGui in the Cargo.toml file but how do I open the menu?

![image](https://user-images.githubusercontent.com/31520916/57102717-0dd3b180-6d1c-11e9-9e29-2f264e8cf9f5.png)
This picture includes the Injector with the injection method, the Yuki Console and where the dynamic link library file is.

Appreciate the effort you put in for this hack <3

**Comment by Proximyst** [comment]
If you had read the README, there is no proper functionality in this yet; it is simply an evolving base for now. ImGui is going to be used to make, well, GUIs (but in a type-safe fashion!), but for now everything here is simply a big WIP.
